#include "ESpectrum.h"

int main(int argc, char *argv[])
{

  FILE *inp, *output;
  char str[16][132];
  double deltaExi, binfactor;
  double exi,initExi;
  bool first = true;;

  if(argc!=3)
    {
      printf("PACE_DeltaExi_FirstParticle particles_file binning\n");
      printf("\nGenerates a spectrum (histogram) of excitation energy (in MeV) for particles in the input\n.particles file generated by PACE4.\n");
      printf("Particles are gated by the initial excitation energy (in MeV) of the\ncompound nucleus such that only the first emitted particles are.\n");
      printf("The binning parameter is in MeV/channel (recommend 0.1 or higher as\n.particle files report energies to 0.1 MeV).\n");
      exit(-1);
    }

  //read in command line arguments
  if((inp=fopen(argv[1],"r"))==NULL)
      {
         printf("\nFile %s can not be opened\n",argv[1]);
         exit(-1);
      }
  binfactor=1./atof(argv[2]);

  //read the .particles file and build the output histogram
  if(fgets(str[0],132,inp)!=NULL)
    {
    if(fgets(str[0],132,inp)!=NULL)
      while(fscanf(inp,"%s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s",str[0],str[1],str[2],str[3],str[4],str[5],str[6],str[7],str[8],str[9],str[10],str[11],str[12],str[13],str[14],str[15])!=EOF)
	{
          if (first == true)
            {
              first = false;
              initExi = atof(str[12]);
              printf("Initial excitation energy of the first particle is %f MeV.\n", initExi);
            }
          exi = atof(str[12]); //get Exi of the compund nucleus
          if(exi==initExi) //get the gate
            {
              deltaExi = binfactor*(atof(str[12]) - atof(str[13])); //get delta Exi of the particle
              hist[(int)deltaExi]++;
            }
        }
    else
      {
        printf("Wrong structure of file %s.\n",argv[1]);
        printf("Aborting...\n");
        exit(1);
      }
    }
  else
    {
      printf("Wrong structure of file %s.\n",argv[1]);
      printf("Aborting...\n");
      exit(1);
    }

  //write the output histogram to disk
  if((output=fopen("DeltaExi_FirstParticle.mca","w"))==NULL)
    {
      printf("ERROR!!! I cannot open the mca file!\n");
      exit(EXIT_FAILURE);
    }
  fwrite(hist,S32K*sizeof(int),1,output);
  fclose(output);

  return(1); //great success
}
