#include "ESpectrum.h"

int main(int argc, char *argv[])
{

  FILE *inp, *output;
  char str[16][132];
  double e_lab, binfactor;
  double exi,min,max;

  if(argc!=5)
    {
      printf("ESpectrum_gateExi particles_file min max binning\n");
      printf("\nGenerates an energy spectrum (histogram) for particles in the input .particles file generated by PACE4.\n");
      printf("Particles are gated by the initial excitation energy (in MeV) of the compound nucleus via the 'min' and 'max' parameters.\n");
      printf("The binning parameter is in MeV/channel (recommend 0.1 or higher as .particle files report energies to 0.1 MeV).\n");
      exit(-1);
    }

  //read in command line arguments
  if((inp=fopen(argv[1],"r"))==NULL)
      {
         printf("\nFile %s can not be opened\n",argv[1]);
         exit(-1);
      }
  min=atof(argv[2]);
  max=atof(argv[3]);
  binfactor=1./atof(argv[4]);

  //read the .particles file and build the output histogram
  if(fgets(str[0],132,inp)!=NULL)
    {
    if(fgets(str[0],132,inp)!=NULL)
      while(fscanf(inp,"%s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s",str[0],str[1],str[2],str[3],str[4],str[5],str[6],str[7],str[8],str[9],str[10],str[11],str[12],str[13],str[14],str[15])!=EOF)
	{
          exi = atof(str[12]); //get Exi of the particle
          if((exi<=max)&&(exi>=min)) //get the gate
            {
              e_lab = binfactor*atof(str[14]); //get lab energy of the particle
              hist[(int)e_lab]++;
            }
        }
    else
      {
	printf("Wrong structure of file %s\n",argv[1]);
	printf("Aborting sort\n");
	exit(1);
      }
    }
  else
    {
      printf("Wrong structure of file %s\n",argv[1]);
      printf("Aborting sort\n");
      exit(1);
    }

  //write the output histogram to disk
  if((output=fopen("ESpectrum_gateExi.mca","w"))==NULL)
    {
      printf("ERROR!!! I cannot open the mca file!\n");
      exit(EXIT_FAILURE);
    }
  fwrite(hist,S32K*sizeof(int),1,output);
  fclose(output);

  return(1); //great success
}
