#include "ExiVsInitialSpin.h"

int main(int argc, char *argv[])
{
  FILE *inp;
  char str[16][132];
  int ji;
  double exi;
  
  //ROOT stuff
  int ac;
  char* av[10];
  theApp=new TApplication("App", &ac, av);

  if(argc!=2)
    {
      printf("PACE_ExiVsInitialSpin particles_file\n");
      printf("\nGenerates a 2D histogram of inital compound excitation energy against initial compund nucleus\nspins for all events in the input .particles file generated by PACE4.\n");
      exit(-1);
    }

  //read in command line arguments
  if((inp=fopen(argv[1],"r"))==NULL)
      {
         printf("\nFile %s can not be opened\n",argv[1]);
         exit(-1);
      }

  //set up ROOT canvas and histogram
  if(h!=NULL)
    delete h;
  h=new TH2D("ExiVsInitialSpin","ExiVsInitialSpin",50,0,50,500,0,50);
  if(c!=NULL)
    delete c;
  c = new TCanvas("ExiVsInitialSpin","ExiVsInitialSpin",10,10, 700, 500);

  //read the .particles file and build the output histogram
  if(fgets(str[0],132,inp)!=NULL)
    {
    if(fgets(str[0],132,inp)!=NULL)
      while(fscanf(inp,"%s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s",str[0],str[1],str[2],str[3],str[4],str[5],str[6],str[7],str[8],str[9],str[10],str[11],str[12],str[13],str[14],str[15])!=EOF)
	{
          ji = atoi(str[8]); //get initial spin of the compund nucleus
          exi = atof(str[12]); //get Exi of the compund nucleus
          h->Fill(ji,exi);//increment the histogram
        }
    else
      {
	printf("Wrong structure of file %s.\n",argv[1]);
        printf("Aborting...\n");
        exit(1);
      }
    }
  else
    {
      printf("Wrong structure of file %s.\n",argv[1]);
      printf("Aborting...\n");
      exit(1);
    }

  //display and draw the ROOT histrogram
  h->GetXaxis()->SetTitle("J_init");
  h->GetYaxis()->SetTitle("Ex_i (MeV)");
  h->GetYaxis()->SetTitleOffset(1.5);
  h->SetOption("COLZ");
  gStyle->SetPalette(1);
  h->Draw();
  theApp->Run(kTRUE);

  return(1); //great success
}
